export default {
  LOAD_ALL_QUESTIONS: "Quiz/LOAD_ALL_QUESTIONS",
  LOAD_ALL_QUESTIONS_SUCCESS: "Quiz/LOAD_ALL_QUESTIONS_SUCCESS",
  LOAD_ALL_QUESTIONS_FAIL: "Quiz/LOAD_ALL_QUESTIONS_FAIL",
  GO_TO_NEXT_QUESTION: "Quiz/GO_TO_NEXT_QUESTION",
  GO_TO_PREVIOUS_QUESTION: "Quiz/GO_TO_PREVIOUS_QUESTION",
  GO_TO_START_PAGE: "Quiz/GO_TO_START_PAGE",
  GO_TO_FINISH_PAGE: "Quiz/GO_TO_FINISH_PAGE",
};
